# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea327bd348305fc5330dc30df69b6e543cefeea2eb29b00c9a08a14beeada13da94b5c6227861171a9a4ffab0646abf4659b6fd9117ed0eeee7e343dadf4abc2

test:
  secret_key_base: b5f017e55e353ee5a6aeaaf86e03c8da2d58117cc864a6d622d2980511b376b99d474d6e33465e0f07516ec406ec8d8ceadbfca6d9be8479f111384d546a77d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
