picture_cate_size: 5
max_cate_name: 50
min_cate_name: 10
max_cate_desc: 100
valid_picture: "image/jpeg,image/gif,image/png"

user:
  max_name_length: 50
  max_email_length: 255
  min_password_length: 6
  password_reset_time_expired: 2
  param_pages_users: 20
  avatar: 50
gravatar:
  gravatar_size: 80
  gravatar_micropost_size: 50
