user:
  max_name_length: 50
  max_email_length: 255
  min_password_length: 6
  password_reset_time_expired: 2
  param_pages_users: 20
  avatar: 50
  per_page: 20
  small_avatar: 30
gravatar:
  gravatar_size: 80
  gravatar_micropost_size: 50
category:
  picture_cate_size: 5
  max_cate_name: 50
  min_cate_name: 10
  max_cate_desc: 100
  valid_picture: "image/jpeg,image/gif,image/png"
  cate_per_page: 6
  picture_cate_width: 400
  picture_cate_height: 400
lesson:
  word_per_lesson: 10
  limit_lesson: 3
result:
  single_answer: 1
word:
  picture_size: 100
  per_page: 20
  max_length_content: 200
answer_count: 0
answer_quanlity: 2
filter_words:
  learned: "learned"
  not_learned: "not_learned"
  learned_correct: "learned_correct"
  learned_not_correct: "learned_not_correct"
  get_all: "get_all"
lesson:
  lesson_per_page: 10
  word_per_lesson: 10
feed:
  per_page: 20
follower:
  per_page: 20
following:
  per_page: 20
activity:
  per_page: 20
  size: 20
